### ISSUE TITLE
0.0.10.1 Doesn't works on Windows 10 & Firefox 48

### ISSUE THREAD

**Issue by Honiix** [GhostText/GhostText#78]
On Windows 10 ver1607, Firefox 48.0, Sublime Text 3 build 3114 says:
> GhostText is starting now…
Setting on request handler
HTTP Start
Package Control: No updated packages
Traceback (most recent call last):
  File "./python3.3/subprocess.py", line 1104, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 553, in run_
    return self.run()
  File "FocusSublimeWindow in C:\Users\laurent\AppData\Roaming\Sublime Text 3\Installed Packages\GhostText.sublime-package", line 24, in run
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1110, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
WebSocketServer id: 1
Setting on message handler
Setting on close handler
Start
Listening on: 50469

If I set the Firefox addon to that port and I click again on the GhostText icon, sublim Text says:

> Traceback (most recent call last):
  File "WebSocket.WebSocketServer in C:\Users\laurent\AppData\Roaming\Sublime Text 3\Installed Packages\GhostText.sublime-package", line 62, in start
  File "WebSocket.Frame in C:\Users\laurent\AppData\Roaming\Sublime Text 3\Installed Packages\GhostText.sublime-package", line 52, in parse
IndexError: index out of range
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "GhostText in C:\Users\laurent\AppData\Roaming\Sublime Text 3\Installed Packages\GhostText.sublime-package", line 33, in run
  File "WebSocket.WebSocketServer in C:\Users\laurent\AppData\Roaming\Sublime Text 3\Installed Packages\GhostText.sublime-package", line 64, in start
UnboundLocalError: local variable 'e' referenced before assignment

But, in the mean time, Chrome, on the same computer, works fine!?

Any Idea?

**Comment by bfred-it** [comment]
The old GT-Firefox had a few issues and is unsupported at this point, hopefully we'll get the new cross-browser version out. If you would like to contribute, try out what's in the "browser" folder in this repo

**Comment by Honiix** [comment]
Oh ok, Thanks. I'll check that folder.
Or use Chrome ;) This addon is so convenient! Nice work!

**Comment by bfred-it** [comment]
The new GhostText Firefox extension has been published https://addons.mozilla.org/en-US/firefox/addon/ghosttext/ :)
